# name: Code formatting
# on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install .
      - run: npm run check
