# Execute to check code formatting on pull request and push to main/dev branch
name: Code formatting
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install .
      - run: npm run check
