# Execute weekly and publish results to report portal
name: Report portal weekly
on:
  pull_request:
  # To trigger job manually
  workflow_dispatch:
  
  # To schedule job
  schedule:
      # At 00:00 on Sunday
    - cron: 0 0 * * 0

jobs:
  cypress-run:
    name: Cypress run weekly
    runs-on: self-hosted
    strategy:
      matrix:
        branch: [main]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: tackle-ui-tests
          ref: ${{ matrix.branch }}
        # Install NPM dependencies
      - name: Install NPM
        run: npm install .
        # Run cypress integration tests and upload results to report portal
      - name: Run cypress test cases and publish results to report portal
        run: |
          export RP_TOKEN=${{ secrets.REPORT_TOKEN }}
          export RP_ENDPOINT=${{ secrets.PORTAL_ENDPOINT }}
          export RP_LAUNCH="Tackle-1.0-weekly"
          npx cypress run --spec **/login.test.ts --env user=${{ secrets.TACKLE_USER }},pass=${{ secrets.TACKLE_PASS }},tackleUrl=${{ secrets.TACKLE_URL }} --config-file reportconfig.json
